### ISSUE TITLE
Update package.json with script path

### ISSUE THREAD

**Issue by yoyurec** [resrcit/resrc.js#5]
To use **requre('resrc.js')** in browserify `package.json` should be updated with script path:
```
...
  "main": "src/resrc.js",
...
```
for ex.: https://github.com/jquery/jquery/blob/master/package.json#L6

**Comment by domfee** [comment]
@yoyurec Cheers for this dude. This has now been added to v0.9.2: 

*https://github.com/resrcit/resrc.js/blob/v0.9.2/package.json#L6

We will be pushing this to MAIN very shortly.

**Comment by domfee** [comment]
@yoyurec This is now in main.
