### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by jontelm** [resrcit/resrc.js#7]
Uncaught TypeError: Cannot read property 'length' of null

v0.93

**Comment by domfee** [comment]
@jontelm  Could do with a bit more context please.

**Comment by jontelm** [comment]
I missed added domain, was using relative path.

**Comment by domfee** [comment]
We handle the error cleaner in the upcoming 0.10.0 release.

**Comment by domfee** [comment]
Fixed: https://github.com/resrcit/resrc.js/releases/tag/v0.9.5
